version: '3.3'
services:
  db:
    container_name: playground-db
    image: mysql:5
    volumes:
      - "./.db:/var/lib/mysql"
    restart: "no"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
    environment:
      MYSQL_ROOT_PASSWORD: dev
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev